services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - app-network
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/home/app
networks:
  app-network:
    driver: bridge

